### ISSUE TITLE
Enhance UI of settings page its empty and can have more good UI and UX

### ISSUE THREAD

**Issue by kaurjasleen240305** [sugarlabs/make-them-fall-activity#35]
PROBLEM:
I saw settings page it has below problems 
->Much of the space in that screen is empty which is not a feature of good UI

->Poor UX until and unless user does not clicks Difficulty button he does not knows how to change difficulty for him/her.

SOLUTION:
We can have three different buttons for three levels i.e. DIFFICULT, EASY,MEDIUM and three of them can be displayed on that screen accordingly user will select the button accord to his level of comfort 

Features:-
->Covers much space in page and has much better UI than previous settings screen.
->More reliable for children to choose difficulty level and guess how to do it

**Comment by quozl** [comment]
Please don't open an issue if you are planning to open a pull request. Just open the pull request instead. Issues are best used for things you are not going to fix, and hope someone else will fix them.

Please do read https://github.com/sugarlabs/sugar-docs/blob/master/src/
contributing.md
