### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/make-them-fall-activity#7]

**Comment by iamutkarshtiwari** [comment]
https://github.com/sugarlabs/make-them-fall-activity/commit/4ca80f60d8791dfc12e2557ed43852482d7fb694

**Comment by quozl** [comment]
good progress, more work needed, setup.py is GTK+ 2.

**Comment by yashagrawal3** [comment]
This issue can now be closed ```6105d83```

**Comment by quozl** [comment]
6105d83
